Metrics/AbcSize:
  Enabled: true

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - "**/*.gemspec"
    - "**/Rakefile"
    - "**/*.rake"
    - "spec/**/*.rb"

Metrics/CyclomaticComplexity:
  Enabled: true

Metrics/ParameterLists:
  Enabled: true

Metrics/PerceivedComplexity:
  Enabled: true
