Naming/AsciiIdentifiers:
  Enabled: true

Naming/BinaryOperatorParameterName:
  Enabled: true

Naming/ClassAndModuleCamelCase:
  Enabled: true

Naming/FileName:
  Enabled: true

Naming/HeredocDelimiterNaming:
  Enabled: true

Naming/VariableName:
  Enabled: true
