Style/AndOr:
  Enabled: true
  EnforcedStyle: conditionals

Style/ArrayJoin:
  Enabled: true

Style/Attr:
  Enabled: true

Style/AutoResourceCleanup:
  Enabled: true

Style/BlockComments:
  Enabled: true

Style/BlockDelimiters:
  Enabled: true
  EnforcedStyle: line_count_based

Style/CharacterLiteral:
  Enabled: true

Style/ClassAndModuleChildren:
  Enabled: true
  EnforcedStyle: nested

Style/ClassCheck:
  Enabled: true

Style/ClassVars:
  Enabled: true

Style/CollectionMethods:
  Enabled: true
  PreferredMethods:
    collect: map
    collect!: map!
    inject: reduce
    detect: find
    find_all: select

Style/ClassMethods:
  Enabled: true

Style/ColonMethodDefinition:
  Enabled: true

Style/ColonMethodCall:
  Enabled: true

Style/CommandLiteral:
  Enabled: true
  EnforcedStyle: backticks

Style/CommentAnnotation:
  Enabled: true

Style/ConditionalAssignment:
  Enabled: true
  EnforcedStyle: assign_to_condition

Style/ConstantVisibility:
  Enabled: true

Style/DefWithParentheses:
  Enabled: true

Style/Dir:
  Enabled: true

Style/EachForSimpleLoop:
  Enabled: true

Style/EmptyBlockParameter:
  Enabled: true

Style/EmptyElse:
  Enabled: true

Style/EmptyLambdaParameter:
  Enabled: true

Style/EmptyMethod:
  Enabled: true
  EnforcedStyle: expanded

Style/Encoding:
  Enabled: true

Style/EndBlock:
  Enabled: true

Style/ExpandPathArguments:
  Enabled: true

Style/FloatDivision:
  Enabled: true
  EnforcedStyle: fdiv

Style/For:
  Enabled: true
  EnforcedStyle: each

Style/FormatString:
  Enabled: true
  EnforcedStyle: format

Style/FormatStringToken:
  Enabled: true
  EnforcedStyle: template

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Style/GlobalVars:
  Enabled: true

Style/HashSyntax:
  Enabled: true
  EnforcedStyle: no_mixed_keys

Style/IdenticalConditionalBranches:
  Enabled: true

Style/IfUnlessModifierOfIfUnless:
  Enabled: true

Style/IfWithSemicolon:
  Enabled: true

Style/InfiniteLoop:
  Enabled: true

Style/Lambda:
  Enabled: true
  EnforcedStyle: literal

Style/LambdaCall:
  Enabled: true
  EnforcedStyle: braces

Style/MethodCallWithoutArgsParentheses:
  Enabled: true

Style/MethodDefParentheses:
  Enabled: true
  EnforcedStyle: require_parentheses

Style/MinMax:
  Enabled: true

Style/MissingRespondToMissing:
  Enabled: true

Style/MixinGrouping:
  Enabled: true
  EnforcedStyle: separated

Style/MixinUsage:
  Enabled: true

Style/MultilineIfModifier:
  Enabled: true

Style/MultilineMemoization:
  Enabled: true
  EnforcedStyle: keyword

Style/MultilineTernaryOperator:
  Enabled: true

Style/MultilineWhenThen:
  Enabled: true

Style/MutableConstant:
  Enabled: true

Style/NegatedIf:
  Enabled: true
  EnforcedStyle: both

Style/NegatedUnless:
  EnforcedStyle: both

Style/NestedModifier:
  Enabled: true

Style/NestedTernaryOperator:
  Enabled: true

Style/NilComparison:
  Enabled: true
  EnforcedStyle: predicate

Style/NonNilCheck:
  Enabled: true

Style/Not:
  Enabled: true

Style/NumericLiteralPrefix:
  Enabled: true
  EnforcedOctalStyle: zero_with_o

Style/NumericLiterals:
  Enabled: true

Style/OneLineConditional:
  Enabled: true

Style/OptionHash:
  Enabled: true

Style/OptionalArguments:
  Enabled: true

Style/OrAssignment:
  Enabled: true

Style/ParenthesesAroundCondition:
  Enabled: true
  AllowInMultilineConditions: false

Style/PercentLiteralDelimiters:
  Enabled: true

Style/PerlBackrefs:
  Enabled: true

Style/PreferredHashMethods:
  Enabled: true
  EnforcedStyle: verbose

Style/Proc:
  Enabled: true

Style/RaiseArgs:
  Enabled: true
  EnforcedStyle: exploded

Style/RandomWithOffset:
  Enabled: true

Style/RedundantBegin:
  Enabled: true

Style/RedundantConditional:
  Enabled: true

Style/RedundantException:
  Enabled: true

Style/RedundantFreeze:
  Enabled: true

Style/RedundantParentheses:
  Enabled: true

Style/RedundantReturn:
  Enabled: true

Style/RedundantSelf:
  Enabled: true

Style/RedundantSortBy:
  Enabled: true

Style/RescueStandardError:
  Enabled: true

Style/SafeNavigation:
  Enabled: true

Style/Sample:
  Enabled: true

Style/SelfAssignment:
  Enabled: true

Style/Semicolon:
  Enabled: true
  AllowAsExpressionSeparator: true

Style/Send:
  Enabled: true

Style/SignalException:
  Enabled: true
  EnforcedStyle: only_raise

Style/SingleLineMethods:
  Enabled: true
  AllowIfMethodIsEmpty: false

Style/SpecialGlobalVars:
  Enabled: true
  EnforcedStyle: use_english_names

Style/StabbyLambdaParentheses:
  Enabled: true
  EnforcedStyle: require_parentheses

Style/StderrPuts:
  Enabled: true

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringMethods:
  Enabled: true

Style/Strip:
  Enabled: true

Style/StructInheritance:
  Enabled: true

Style/SymbolArray:
  Enabled: true
  EnforcedStyle: brackets

Style/WordArray:
  Enabled: true
  EnforcedStyle: brackets

Style/SymbolLiteral:
  Enabled: true

Style/SymbolProc:
  Enabled: true

Style/TernaryParentheses:
  Enabled: true
  EnforcedStyle: require_no_parentheses

Style/TrailingBodyOnClass:
  Enabled: true

Style/TrailingBodyOnMethodDefinition:
  Enabled: true

Style/TrailingBodyOnModule:
  Enabled: true

Style/TrailingCommaInArguments:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/TrailingMethodEndStatement:
  Enabled: true

Style/TrailingUnderscoreVariable:
  Enabled: true

Style/TrivialAccessors:
  Enabled: true

Style/UnlessElse:
  Enabled: true

Style/RedundantCondition:
  Enabled: true

Style/RedundantSort:
  Enabled: true

Style/UnpackFirst:
  Enabled: true

Style/VariableInterpolation:
  Enabled: true

Style/WhenThen:
  Enabled: true

Style/WhileUntilDo:
  Enabled: true

Style/YodaCondition:
  Enabled: true
  EnforcedStyle: forbid_for_all_comparison_operators
